name: Deploy
on:
  push:
    branches:
      - new-main
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v3        
      - name: Config git
        run: |
          git config --global user.name Rodrigo 
          git config --global user.email rcarmona@realmetrics.io
      - name: Add Remote
        env:
          TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git add .
          git commit -m "Automated sync from main repository" || echo "No changes to commit"
          git remote add secondary https://$TOKEN@github.com/usuario/Rodcarm/gitAccionTest.git
          git push -u secundary new-main